# Render Blueprint for FinPrintIQ API

services:
  - type: web
    name: finprintiq-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app --timeout 180
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PORT
        value: 10000
      # Add your environment variables here
      - key: DATABASE_URL
        fromDatabase:
          name: finprintiq-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production

databases:
  - name: finprintiq-db
    databaseName: finprintiq
    user: finprintiq_user
    plan: free
